CC = cc  
CFLAGS = -O
LIBS = -lm -lX11
DESTBIN = /usr/bin/X11
DESTMAN = /usr/man/manl

hop: hop.o
	$(CC) $(CFLAGS) -o hop hop.o $(LIBS)

hop.o: hop.c hop.h patchlevel.h
	$(CC) $(CFLAGS) -c hop.c

install: hop
	cp hop $(DESTBIN)/hop;
	cd $(DESTBIN); chmod 755 hop

install.man:
	cp hop.man $(DESTMAN)/hop.l; chmod 644 $(DESTMAN)/hop.l
      
clean:
	rm -f hop hop.o core

uninstall:
	cd $(DESTBIN); rm -f hop
	rm -f $(DESTMAN)/hop.l
